Repository divine-craft/skyblock-resourcepack, pull requests merged in 2020-06, with the labels that each got.

#2 Palladium
  .gitattributes
  assets/minecraft/textures/divinecraft/item/palladium_ingot.png
  assets/minecraft/textures/divinecraft/item/palladium_ingot.png.mcmeta
Labels: enhancement

#7 Gidrit
  assets/minecraft/textures/divinecraft/item/gidrit.png
  assets/minecraft/textures/divinecraft/item/gidrit.png.mcmeta
  assets/minecraft/textures/divinecraft/item/microchip.png
Labels: enhancement

#8 Linkers
  assets/minecraft/textures/divinecraft/item/item_teleport_linker.png
  assets/minecraft/textures/divinecraft/item/teleport_linker.png
Labels: enhancement

#9 unnamed_ore
  assets/minecraft/textures/divinecraft/item/unnamed_ore.png
  assets/minecraft/textures/divinecraft/item/unnamed_ore.png.mcmeta
Labels: enhancement

#10 Create Tourmaline Bblock
  assets/minecraft/models/divinecraft/block/tourmaline_block.json
  assets/minecraft/textures/divinecraft/texture/tourmaline_block.png
Labels: enhancement

#11 titan_ingot
  assets/minecraft/textures/divinecraft/item/titan_ingot.png
Labels: enhancement

#12 Add Item Models
  assets/minecraft/models/divinecraft/item/gidrit.json
  assets/minecraft/models/divinecraft/item/item_teleport_linker.json
  assets/minecraft/models/divinecraft/item/microchip.json
  assets/minecraft/models/divinecraft/item/palladium_ingot.json
  assets/minecraft/models/divinecraft/item/teleport_linker.json
  assets/minecraft/models/divinecraft/item/titan_ingot.json
  assets/minecraft/models/divinecraft/item/unnamed_ore.json
Labels: enhancement

#13 Add Tourmaline blocks
  assets/minecraft/models/divinecraft/block/tourmaline_block.json
  assets/minecraft/models/divinecraft/block/tourmaline_ore.json
  assets/minecraft/textures/divinecraft/block/tourmaline_block.png
  assets/minecraft/textures/divinecraft/block/tourmaline_ore.png
Labels: enhancement

#18 copper_ore
  assets/minecraft/models/divinecraft/block/copper_ore.json
  assets/minecraft/textures/divinecraft/block/copper_ore.png
Labels: enhancement

#17 copper_block
  assets/minecraft/models/divinecraft/block/copper_block.json
  assets/minecraft/textures/divinecraft/block/copper_block.png
Labels: enhancement

#1 Implement initail structure
  .gitignore
  .travis.yml
  assets/divinecraft/models/block/copper_block.json
  assets/divinecraft/models/block/copper_ore.json
  assets/divinecraft/models/block/machine_casing.json
  assets/divinecraft/models/block/tourmaline_block.json
  assets/divinecraft/models/block/tourmaline_ore.json
  assets/divinecraft/models/item/gidrit.json
  assets/divinecraft/models/item/item_teleport_linker.json
  assets/divinecraft/models/item/microchip.json
  assets/divinecraft/models/item/palladium_ingot.json
  assets/divinecraft/models/item/teleport_linker.json
  assets/divinecraft/models/item/titanium_ingot.json
  assets/divinecraft/models/item/unnamed_ore.json
  assets/divinecraft/textures/block/copper_block.png
  assets/divinecraft/textures/block/copper_ore.png
  assets/divinecraft/textures/block/machine_casing.png
  assets/divinecraft/textures/block/tourmaline_block.png
  assets/divinecraft/textures/block/tourmaline_ore.png
  assets/divinecraft/textures/item/gidrit.png
  assets/divinecraft/textures/item/gidrit.png.mcmeta
  assets/divinecraft/textures/item/item_teleport_linker.png
  assets/divinecraft/textures/item/microchip.png
  assets/divinecraft/textures/item/palladium_ingot.png
  assets/divinecraft/textures/item/palladium_ingot.png.mcmeta
  assets/divinecraft/textures/item/teleport_linker.png
  assets/divinecraft/textures/item/titanium_ingot.png
  assets/divinecraft/textures/item/unnamed_ore.png
  assets/divinecraft/textures/item/unnamed_ore.png.mcmeta
  description.txt
  mappings/diamond_axe.csv
  mappings/diamond_hoe.csv
  mappings/diamond_shovel.csv
  pack.png
  requirements.txt
  scripts/compress_models.py
  scripts/generate_multimodels.py
  scripts/generate_pack_mcmeta.py
  scripts/generate_resourcepacks.sh
  scripts/patch_v2_models_to_v3.py
Labels: enhancement

#23 bronze_ingot
  assets/divinecraft/models/item/bronze_ingot.json
  assets/divinecraft/textures/item/bronze_ingot.png
Labels: enhancement

#22 tin_ingot
  assets/divinecraft/models/item/tin_ingot.json
  assets/divinecraft/textures/item/tin_ingot.png
Labels: enhancement

#24 Fix releases' deployment
  .travis.yml
Labels: enhancement

#25 Fix model display for non-unbreakable items
  scripts/generate_multimodels.py
Labels: bug

#26 Update README.md & fix `pack_format` versions
  .travis.yml
  README.md
  scripts/generate_resourcepacks.sh
  scripts/patch_v3_models_to_v4.py
Labels: bug, documentation, enhancement

#27 Teleporter
  assets/divinecraft/models/block/teleporter_1.json
  assets/divinecraft/textures/block/teleporter_1.png
  assets/divinecraft/textures/block/teleporter_1_down.png
  assets/divinecraft/textures/block/teleporter_1_up.png
  mappings/diamond_hoe.csv
Labels: enhancement

#30 Add All 1 Tier
  assets/divinecraft/models/block/autofarmer_1.json
  assets/divinecraft/models/block/breaker_1.json
  assets/divinecraft/models/block/compressor_1.json
  assets/divinecraft/models/block/item_sucker_1.json
  assets/divinecraft/models/block/placer_1.json
  assets/divinecraft/models/block/stacker_1.json
  assets/divinecraft/models/block/teleporter_1.json
  assets/divinecraft/textures/block/compressor_1.png
  assets/divinecraft/textures/block/compressor_1_back.png
  assets/divinecraft/textures/block/compressor_1_left.png
  assets/divinecraft/textures/block/compressor_1_right.png
  assets/divinecraft/textures/block/compressor_1_up.png
  assets/divinecraft/textures/block/item_sucker_1_left.png
  assets/divinecraft/textures/block/item_sucker_1_right.png
  assets/divinecraft/textures/block/placer_1_pipes.png
  mappings/diamond_hoe.csv
Labels: enhancement

#31 add 2 tier "autofarmer,breaker,comperssor"
  assets/divinecraft/models/block/autofarmer_2.json
  assets/divinecraft/models/block/breaker_2.json
  assets/divinecraft/models/block/compressor_2.json
  assets/divinecraft/textures/block/saw.png
  assets/divinecraft/textures/block/saw.png.mcmeta
  assets/divinecraft/textures/block/wheat_animation.png
  assets/divinecraft/textures/block/wheat_animation.png.mcmeta
Labels: enhancement

#32 5 tier compressor, breaker
  assets/divinecraft/models/block/breaker_5.json
  assets/divinecraft/models/block/compressor_5.json
  assets/divinecraft/textures/block/breaker_5.png
  assets/divinecraft/textures/block/breaker_5.png.mcmeta
  assets/divinecraft/textures/block/breaker_5_up.png
  assets/divinecraft/textures/block/compressor_5.png
  assets/divinecraft/textures/block/compressor_5_down.png
  assets/divinecraft/textures/block/compressor_5_down2.png
  assets/divinecraft/textures/block/compressor_5_face.png
  assets/divinecraft/textures/block/crafting_display.png
  assets/divinecraft/textures/block/crafting_display.png.mcmeta
  assets/divinecraft/textures/skin/_kreeper_rus.png
Labels: enhancement

#33 Fix typo in README's endpoint reference
  README.md
Labels: bug

#34 Fixed Breaker 1 texture
  assets/divinecraft/textures/block/breaker_1_face.png
Labels: bug

#35 Texture names patcher
  assets/divinecraft/models/block/teleporter_1.json
  scripts/mappings/v3_v4/block_textures.csv
  scripts/mappings/v3_v4/item_textures.csv
  scripts/patch_v3_models_to_v4.py
Labels: bug, enhancement

#37 Create item_sucker_2.json
  assets/divinecraft/models/block/item_sucker_2.json
Labels: enhancement

#39 Rename `gidrit` to `gidrit_dust`
  assets/divinecraft/models/item/gidrit_dust.json
  assets/divinecraft/textures/item/gidrit_dust.png
  assets/divinecraft/textures/item/gidrit_dust.png.mcmeta
Labels: bug

#42 tin_block
  assets/divinecraft/models/block/tin_block.json
  assets/divinecraft/textures/block/tin_block.png
Labels: enhancement

#41 Add compressor_4
  assets/divinecraft/models/block/compressor_4.json
  assets/divinecraft/textures/block/compressor_4_controller.png
  assets/divinecraft/textures/block/compressor_4_down.png
  assets/divinecraft/textures/block/compressor_4_down_inside.png
  assets/divinecraft/textures/block/compressor_4_face.png
  assets/divinecraft/textures/block/compressor_4_inside.png
  assets/divinecraft/textures/block/compressor_4_side.png
  assets/divinecraft/textures/block/compressor_4_up.png
Labels: enhancement

#44 Fix stacker_1 missing texture
  assets/divinecraft/models/block/stacker_1.json
Labels: bug

#45 Fix `placer_1_pipes` texture reference in `stacker_1`
  assets/divinecraft/models/block/stacker_1.json
Labels: bug

#46 Add placer_4
  assets/divinecraft/models/block/placer_4.json
  assets/divinecraft/textures/block/placer_4_front.png
  assets/divinecraft/textures/block/placer_4_pipe.png
  assets/divinecraft/textures/block/placer_4_side.png
  assets/divinecraft/textures/block/placer_4_side_2.png
  assets/divinecraft/textures/block/placer_4_side_3.png
  assets/divinecraft/textures/block/placer_4_up.png
Labels: enhancement

#47 Add teleporter_2
  assets/divinecraft/models/block/teleporter_2.json
  assets/divinecraft/textures/block/teleporter_2_down.png
  assets/divinecraft/textures/block/teleporter_2_side.png
  assets/divinecraft/textures/block/teleporter_2_up.png
  assets/divinecraft/textures/block/teleporter_2_up.png.mcmeta
Labels: enhancement

#48 Compressor 2 assets fixes
  assets/divinecraft/models/block/compressor_2.json
Labels: bug

#51 Tin ore
  assets/divinecraft/models/block/tin_ore.json
  assets/divinecraft/textures/block/tin_ore.png
Labels: enhancement

#50 titanium_ore
  assets/divinecraft/models/block/titanium_ore.json
  assets/divinecraft/textures/block/titanium_ore.png
Labels: enhancement

#49 tourmaline
  assets/divinecraft/models/item/tourmaline.json
  assets/divinecraft/textures/item/tourmaline.png
Labels: enhancement

#53 gidora_paw
  assets/divinecraft/models/item/gidora_paw.json
  assets/divinecraft/textures/item/gidora_paw.png
Labels: enhancement

#52 copper_ingot
  assets/divinecraft/models/item/copper_ingot.json
  assets/divinecraft/textures/item/copper_ingot.png
Labels: enhancement

#54 Fix linker names
  assets/divinecraft/models/item/item_sucker_linker.json
  assets/divinecraft/models/item/teleporter_linker.json
  assets/divinecraft/textures/item/item_sucker_linker.png
  assets/divinecraft/textures/item/teleporter_linker.png
Labels: bug

#55 Create autofarmer_5.json
  assets/divinecraft/models/block/autofarmer_5.json
Labels: enhancement

#56 Fixed autofamrmer 5 tier
  assets/divinecraft/models/block/autofarmer_5.json
Labels: bug

#57 add Breaker 3
  assets/divinecraft/models/block/breaker_3.json
  assets/divinecraft/textures/block/breaker_3.png
Labels: enhancement

#58 Created autofarmer_3
  assets/divinecraft/models/block/autofarmer_3.json
Labels: enhancement

#59 Optimize AutoFarmer & Breaker Tier 3 and change their dimensions
  assets/divinecraft/models/block/autofarmer_3.json
  assets/divinecraft/models/block/breaker_3.json
Labels: enhancement

#60 Create compressor_3
  assets/divinecraft/models/block/compressor_3.json
Labels: enhancement

#61 Create Item sucker 3 tier and fix breaker 3 and 2 tier
  assets/divinecraft/models/block/breaker_2.json
  assets/divinecraft/models/block/breaker_3.json
  assets/divinecraft/models/block/item_sucker_3.json
Labels: enhancement

#63 Create placer 2.json
  assets/divinecraft/models/block/placer 2.json
Labels: enhancement

#65 gidora_brisket
  assets/divinecraft/models/item/gidora_brisket.json
  assets/divinecraft/textures/item/gidora_brisket.png
Labels: enhancement

#66 gidora_muzzle
  assets/divinecraft/models/item/gidora_muzzle.json
  assets/divinecraft/textures/item/gidora_muzzle.png
  assets/divinecraft/textures/item/gidora_muzzle.png.mcmeta
Labels: enhancement

#67 Update compressor_5.json
  assets/divinecraft/models/block/compressor_5.json
Labels: bug

#68 Update breaker_2.json
  assets/divinecraft/models/block/breaker_2.json
Labels: bug

#69 Update compressor_5.json
  assets/divinecraft/models/block/compressor_5.json
Labels: bug

#70 jackal_head
  assets/divinecraft/models/item/jackal_head.json
  assets/divinecraft/textures/item/jackal_head.png
Labels: enhancement

#71 gidora_compost
  assets/divinecraft/models/item/gidora_compost.json
  assets/divinecraft/textures/item/gidora_compost.png
  assets/divinecraft/textures/item/gidora_compost.png.mcmeta
Labels: enhancement

#72 Gidora bud
  assets/divinecraft/models/item/gidora_bud.json
  assets/divinecraft/textures/item/gidora_bud.png
Labels: enhancement

#74 Fixed Teleporter 1 and placer 2
  assets/divinecraft/models/block/placer_2.json
  assets/divinecraft/models/block/teleporter_1.json
Labels: bug

#73 Create placer_3.json
  assets/divinecraft/models/block/placer_3.json
Labels: enhancement

#76 gadzilla_liver
  assets/divinecraft/models/item/gadzilla_liver.json
  assets/divinecraft/textures/item/gadzilla_liver.png
Labels: enhancement

#75 Fix item mappings
  assets/divinecraft/models/block/compressor_4.json
  assets/divinecraft/models/block/copper_block.json
  assets/divinecraft/models/block/copper_ore.json
  assets/divinecraft/models/block/machine_casing.json
  assets/divinecraft/models/block/placer 2.json
  assets/divinecraft/models/block/placer_2.json
  assets/divinecraft/models/block/placer_4.json
  assets/divinecraft/models/block/teleporter_2.json
  assets/divinecraft/models/block/tin_block.json
  assets/divinecraft/models/block/tin_ore.json
  assets/divinecraft/models/block/titanium_ore.json
  assets/divinecraft/models/block/tourmaline_block.json
  assets/divinecraft/models/block/tourmaline_ore.json
  assets/divinecraft/models/item/tourmaline_crystal.json
  assets/divinecraft/textures/item/tourmaline_crystal.png
  mappings/diamond_shovel.csv
  scripts/generate_multimodels.py
  scripts/generate_resourcepacks.sh
Labels: bug, enhancement

#77 Fix jackal_head mapping
  mappings/diamond_shovel.csv
Labels: bug

#78 Add remaining tier-4 blocks
  assets/divinecraft/models/block/autofarmer_4.json
  assets/divinecraft/models/block/breaker_4.json
  assets/divinecraft/textures/block/autofarmer_4_down.png
  assets/divinecraft/textures/block/autofarmer_4_flower.png
  assets/divinecraft/textures/block/autofarmer_4_side.png
  assets/divinecraft/textures/block/autofarmer_4_up.png
  assets/divinecraft/textures/block/breaker_4.png
  assets/divinecraft/textures/block/breaker_4_1.png
  assets/divinecraft/textures/block/breaker_4_down.png
  assets/divinecraft/textures/block/breaker_4_down_1.png
  assets/divinecraft/textures/block/breaker_4_side.png
  assets/divinecraft/textures/block/teleporter_2_circle.png
Labels: enhancement

#79 Fix `stone_slab_side` texture mapping
  scripts/mappings/v3_v4/block_textures.csv
Labels: bug

#80 Optimize tier-4 textures
  assets/divinecraft/models/block/autofarmer_4.json
  assets/divinecraft/models/block/breaker_4.json
  assets/divinecraft/models/block/placer_4.json
Labels: bug, enhancement

#81 fix gadzila_liver
  assets/divinecraft/textures/item/gadzilla_liver.png
Labels: enhancement

#83 Fix size of palladium_condenser
  assets/divinecraft/models/block/palladium_condenser.json
Labels: bug

#84 Add missing microchip mapping
  mappings/diamond_shovel.csv
Labels: bug, enhancement

#85 Replace python3 -> python
  scripts/generate_resourcepacks.sh
Labels: bug

#86 Release 1.0.2 fixes
  assets/divinecraft/models/block/compressor_5.json
  description.txt
  mappings/diamond_hoe.csv
Labels: bug
